// Hand-tuned pixel-grid art. Each string is one row; each character is a
// palette key resolved against the `palette` maps below. No real project
// artwork was supplied for this redesign, so these are placeholder pixel
// illustrations — swap in real PNGs (see PixelArt component) when available.

export const feetPairGrid: string[] = [
  ".........NNNNNN........................NNNNNN.........",
  ".........NPPPPN........................NPPPPN.........",
  ".........NPPPPN........................NPPPPN.........",
  ".........NPPPPN........................NPPPPN.........",
  ".........NPPPPN........................NPPPPN.........",
  ".........NPPPPN........................NPPPPN.........",
  ".........NPPPPN........................NPPPPN.........",
  ".......NNHHPPPPNN....................NNHHPPPPNN.......",
  "......NPHHHPPPPPPN..................NPHHHPPPPPPN......",
  "....NNHHHHHPPPPPPPNN..............NNHHHHHPPPPPPPNN....",
  "...NPHHHHHHPPPPPPPPPNN...........NPHHHHHHPPPPPPPPPNN..",
  "...NPHHHHHHPPPPPPPPPPN...........NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN...........NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN...........NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN...........NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN...........NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN...........NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN...........NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN...........NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN...........NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN...........NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN...........NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN...........NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN...........NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN...........NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN...........NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN...........NPHHHHHHPPPPPPPPPPN..",
  "..NPHHHHHHHPPPPPPPPPPPN.........NPHHHHHHHPPPPPPPPPPPN.",
  "..NPHHNHHHHNPPPNPPPNPPN.........NPHNHHHNHPPNPPPPNPPPN.",
  "..NPHN.NPHN.NPN.NPN.NPN.........NPN.NPN.NPN.NPPN.NPPN.",
  "..NPHN.NPHN.NPN.NPN.NPN.........NPN.NPN.NPN.NPPN.NPPN.",
  "..NPHN.NPHN.NPN.NNN.NNN.........NNN.NNN.NPN.NPPN.NPPN.",
  "..NPHN.NNNN.NNN.........................NNN.NNNN.NPPN.",
  "..NNNN...........................................NNNN.",
];

export const footSingleGrid: string[] = [
  ".........NNNNNN.........",
  ".........NPPPPN.........",
  ".........NPPPPN.........",
  ".........NPPPPN.........",
  ".........NPPPPN.........",
  ".........NPPPPN.........",
  ".........NPPPPN.........",
  ".......NNHHPPPPNN.......",
  "......NPHHHPPPPPPN......",
  "....NNHHHHHPPPPPPPNN....",
  "...NPHHHHHHPPPPPPPPPNN..",
  "...NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN..",
  "...NPHHHHHHPPPPPPPPPPN..",
  "..NPHHHHHHHPPPPPPPPPPPN.",
  "..NPHHNHHHHNPPPNPPPNPPN.",
  "..NPHN.NPHN.NPN.NPN.NPN.",
  "..NPHN.NPHN.NPN.NPN.NPN.",
  "..NPHN.NPHN.NPN.NNN.NNN.",
  "..NPHN.NNNN.NNN.........",
  "..NNNN..................",
];

export const coinGrid: string[] = [
  "....................",
  "......NNNNNNNN......",
  "....NNYYDDDDYYNN....",
  "...NYYDDYYYYDDYYN...",
  "..NYDDYHHYYYYYDDYN..",
  "..NYDHHHHYYYYYYDYN..",
  ".NYDYHHHHNNYYYYYDYN.",
  ".NYDHHHHNYYNYYYYDYN.",
  ".NDYHHHHNYYYYYYYYDN.",
  ".NDYYYYYYNNYYYYYYDN.",
  ".NDYYYYYYYYNYYYYYDN.",
  ".NDYYYYYNYYNYYYYYDN.",
  ".NYDYYYYYNNYYYYYDYN.",
  ".NYDYYYYYYYYYYYYDYN.",
  "..NYDYYYYYYYYYYDYN..",
  "..NYDDYYYYYYYYDDYN..",
  "...NYYDDYYYYDDYYN...",
  "....NNYYDDDDYYNN....",
  "......NNNNNNNN......",
  "....................",
];

export const palette = {
  feet: { N: "#101B3D", P: "#F0B596", H: "#FFD0AD" },
  coin: { N: "#101B3D", Y: "#FFD42A", D: "#FFB51B", H: "#FFE873" },
} as const;
